/**
 * Phase 2-D — Longitudinal stress business universe.
 * 10 archetypes × 2 variations (structured / prose intake document) = 20 calibration businesses.
 * Holdout truths (biz-16/17) live in `stress-holdout-universe.ts` and are never used for tuning.
 */

import { eulReul, euroRo } from './josa';

export type StressBusinessTruth = {
  id: string;
  archetype: string;
  docStyle: 'structured' | 'prose';
  documentText: string;
  oneLiner: string;
  customer: string;
  /** Different segment — used for contradiction (no correction cue). */
  customerAlt: string;
  /** Segment the founder corrects to (correction behavior). */
  customerCorrected: string;
  user: string;
  usageFrequency: string;
  payer: string;
  problem: string;
  problemAlt: string;
  alternative: string;
  channel: string;
  differentiation: string;
  validation: string;
  revenue: string;
  teamSize: number;
  city: string;
};

type Seed = Omit<StressBusinessTruth, 'id' | 'docStyle' | 'documentText'>;

function structuredDoc(s: Seed): string {
  return `${s.archetype} 스타트업
타겟: ${s.customer}
핵심 문제: ${s.problem}
구매: ${s.payer}`;
}

function proseDoc(s: Seed): string {
  return `${eulReul(s.oneLiner)} 만들고 있습니다.
${s.customer} 고객이 ${s.problem} 때문에 불편을 겪고, 지금은 ${euroRo(s.alternative)} 버티고 있습니다.`;
}

const SEEDS: Array<[string, Seed, Seed]> = [
  [
    'b2c-saas',
    {
      archetype: 'B2C SaaS',
      oneLiner: '개인 일정·할 일 통합 앱',
      customer: '바쁜 직장인',
      customerAlt: '대학생',
      customerCorrected: '1인 프리랜서 디자이너',
      user: '직장인 본인',
      usageFrequency: '매일',
      payer: '사용자 본인',
      problem: '할 일과 일정이 여러 앱에 흩어지는 문제',
      problemAlt: '운동 습관을 못 만드는 문제',
      alternative: '메모 앱과 캘린더',
      channel: '앱스토어 검색과 인스타그램 광고',
      differentiation: '메일과 메신저에서 할 일을 자동으로 모아주는 점',
      validation: '베타 사용자 50명의 4주 리텐션',
      revenue: '월 구독료',
      teamSize: 4,
      city: '서울',
    },
    {
      archetype: 'B2C SaaS',
      oneLiner: '가계부 자동 정리 앱',
      customer: '사회초년생',
      customerAlt: '은퇴한 50대',
      customerCorrected: '신혼부부',
      user: '사회초년생 본인',
      usageFrequency: '매주',
      payer: '사용자 본인',
      problem: '지출을 기록하지 못해 월말에 돈이 부족한 문제',
      problemAlt: '투자 정보를 찾기 어려운 문제',
      alternative: '엑셀 가계부',
      channel: '유튜브 재테크 채널 협업',
      differentiation: '카드 문자를 자동으로 읽어 분류하는 점',
      validation: '사전 신청자 200명 중 유료 전환율',
      revenue: '프리미엄 구독',
      teamSize: 3,
      city: '판교',
    },
  ],
  [
    'b2b-saas',
    {
      archetype: 'B2B SaaS',
      oneLiner: '중소기업 팀 협업 관리 도구',
      customer: '20~50명 규모 중소기업 팀',
      customerAlt: '대기업 IT 부서',
      customerCorrected: '10명 내외 스타트업 운영팀',
      user: '실무 팀원',
      usageFrequency: '매일',
      payer: '팀장이나 대표',
      problem: '업무 요청이 메신저와 메일에 흩어져 누락되는 문제',
      problemAlt: '급여 계산이 복잡한 문제',
      alternative: '엑셀과 카카오톡 단톡방',
      channel: '중소기업 대표 커뮤니티와 웨비나',
      differentiation: '메신저 요청을 자동으로 업무 카드로 바꾸는 점',
      validation: '파일럿 5개 팀의 누락 건수 감소',
      revenue: '사용자당 월 과금',
      teamSize: 6,
      city: '서울',
    },
    {
      archetype: 'B2B SaaS',
      oneLiner: '세무사 사무실용 고객 자료 수집 도구',
      customer: '소규모 세무사 사무실',
      customerAlt: '대형 회계법인',
      customerCorrected: '1인 세무사',
      user: '사무실 직원',
      usageFrequency: '매일',
      payer: '세무사 대표',
      problem: '고객 증빙 자료를 받는 데 시간이 너무 오래 걸리는 문제',
      problemAlt: '사무실 임대료가 비싼 문제',
      alternative: '이메일과 팩스',
      channel: '세무사회 세미나',
      differentiation: '고객이 사진만 찍으면 자료가 자동 분류되는 점',
      validation: '사무실 3곳의 자료 수집 시간 비교',
      revenue: '사무실당 연 구독',
      teamSize: 5,
      city: '대전',
    },
  ],
  [
    'marketplace',
    {
      archetype: 'Marketplace',
      oneLiner: '중소기업과 프리랜서 전문가 매칭 플랫폼',
      customer: '전문 인력이 필요한 중소기업',
      customerAlt: '취업 준비생',
      customerCorrected: '초기 스타트업 대표',
      user: '중소기업 담당자',
      usageFrequency: '프로젝트가 생길 때마다',
      payer: '의뢰하는 기업',
      problem: '검증된 전문가를 빨리 찾기 어려운 문제',
      problemAlt: '사무실 공간이 부족한 문제',
      alternative: '지인 소개와 크몽',
      channel: '창업 지원센터 제휴',
      differentiation: '과거 프로젝트 성과로 전문가를 검증하는 점',
      validation: '첫 20건 매칭의 재의뢰율',
      revenue: '거래 수수료',
      teamSize: 5,
      city: '서울',
    },
    {
      archetype: 'Marketplace',
      oneLiner: '반려동물 돌봄 매칭 서비스',
      customer: '맞벌이 반려인',
      customerAlt: '수의사',
      customerCorrected: '1인 가구 반려인',
      user: '반려인',
      usageFrequency: '출장이나 야근이 있을 때',
      payer: '반려인',
      problem: '믿고 맡길 돌봄 인력을 찾기 어려운 문제',
      problemAlt: '사료 가격이 오르는 문제',
      alternative: '동네 펫호텔',
      channel: '반려동물 커뮤니티 카페',
      differentiation: '돌봄 과정을 실시간 영상으로 보여주는 점',
      validation: '시범 지역 100건 예약 후 만족도',
      revenue: '예약당 수수료',
      teamSize: 4,
      city: '부산',
    },
  ],
  [
    'commerce',
    {
      archetype: 'Commerce',
      oneLiner: '저당 건강 간식 D2C 브랜드',
      customer: '다이어트 중인 20~30대 여성',
      customerAlt: '어린이 자녀를 둔 부모',
      customerCorrected: '당뇨 관리가 필요한 40대',
      user: '구매자 본인',
      usageFrequency: '매일 간식 시간',
      payer: '구매자 본인',
      problem: '맛있으면서 당이 낮은 간식을 찾기 어려운 문제',
      problemAlt: '배송이 느린 문제',
      alternative: '편의점 단백질 바',
      channel: '인스타그램 인플루언서 공동구매',
      differentiation: '설탕 대신 알룰로스로 맛을 유지한 점',
      validation: '첫 달 재구매율',
      revenue: '제품 판매 마진',
      teamSize: 3,
      city: '성수',
    },
    {
      archetype: 'Commerce',
      oneLiner: '캠핑용품 렌탈 커머스',
      customer: '캠핑 입문 가족',
      customerAlt: '전문 등산가',
      customerCorrected: '캠핑을 처음 해보는 커플',
      user: '캠핑하는 가족',
      usageFrequency: '분기마다',
      payer: '가족 중 부모',
      problem: '장비를 다 사기에는 비용이 부담되는 문제',
      problemAlt: '캠핑장 예약이 어려운 문제',
      alternative: '중고 거래 앱',
      channel: '네이버 캠핑 카페',
      differentiation: '캠핑장으로 바로 배송하고 회수하는 점',
      validation: '시즌 동안 렌탈 50건 후 재이용률',
      revenue: '렌탈 요금',
      teamSize: 4,
      city: '인천',
    },
  ],
  [
    'subscription',
    {
      archetype: 'Subscription',
      oneLiner: '직장인 점심 샐러드 정기배송',
      customer: '오피스 밀집 지역 직장인',
      customerAlt: '고등학생',
      customerCorrected: '재택근무하는 직장인',
      user: '직장인 본인',
      usageFrequency: '평일 매일',
      payer: '직장인 본인이나 회사 복지팀',
      problem: '점심 메뉴 고민과 건강한 식사 부족 문제',
      problemAlt: '출근 시간이 긴 문제',
      alternative: '배달앱과 편의점 도시락',
      channel: '오피스 빌딩 로비 시식 행사',
      differentiation: '전날 밤 주문해도 아침에 신선하게 도착하는 점',
      validation: '2주 무료 체험 후 정기 결제 전환율',
      revenue: '주간 정기 구독',
      teamSize: 7,
      city: '서울',
    },
    {
      archetype: 'Subscription',
      oneLiner: '어린이 영어 그림책 구독',
      customer: '5~7세 자녀를 둔 부모',
      customerAlt: '초등학교 교사',
      customerCorrected: '영어 유치원을 보내지 않는 가정',
      user: '아이와 부모',
      usageFrequency: '매일 잠들기 전',
      payer: '부모',
      problem: '아이 수준에 맞는 영어책을 고르기 어려운 문제',
      problemAlt: '아이가 편식하는 문제',
      alternative: '도서관 대출과 유튜브 영어 영상',
      channel: '맘카페와 육아 인스타그램',
      differentiation: '아이 반응을 보고 다음 달 책을 맞춤 추천하는 점',
      validation: '3개월 유지율',
      revenue: '월 구독료',
      teamSize: 3,
      city: '분당',
    },
  ],
  [
    'local',
    {
      archetype: 'Local',
      oneLiner: '동네 음식점 SNS 홍보 대행 서비스',
      customer: '동네 음식점 사장님',
      customerAlt: '프랜차이즈 본사',
      customerCorrected: '테이크아웃 전문 카페 사장님',
      user: '음식점 사장님',
      usageFrequency: '매주',
      payer: '음식점 사장님',
      problem: '홍보할 시간이 없어 신규 손님이 늘지 않는 문제',
      problemAlt: '주방 인력을 구하기 어려운 문제',
      alternative: '전단지와 지인 입소문',
      channel: '상인회 모임과 방문 영업',
      differentiation: '사진만 보내면 게시물을 대신 만들어 올리는 점',
      validation: '가게 10곳의 한 달 신규 방문 수',
      revenue: '월 정액 대행료',
      teamSize: 3,
      city: '대구',
    },
    {
      archetype: 'Local',
      oneLiner: '동네 세탁소 수거·배송 서비스',
      customer: '아파트 단지 맞벌이 가구',
      customerAlt: '호텔',
      customerCorrected: '1인 가구 직장인',
      user: '맞벌이 가구',
      usageFrequency: '주 1회',
      payer: '가구 구성원',
      problem: '세탁소 영업시간에 맞춰 맡기기 어려운 문제',
      problemAlt: '세탁기 고장이 잦은 문제',
      alternative: '코인 세탁소',
      channel: '아파트 단지 커뮤니티 앱',
      differentiation: '밤에 문 앞에 두면 다음날 받아볼 수 있는 점',
      validation: '단지 2곳의 월 이용 가구 수',
      revenue: '건당 배송비와 세탁 마진',
      teamSize: 4,
      city: '수원',
    },
  ],
  [
    'platform',
    {
      archetype: 'Platform/API',
      oneLiner: '쇼핑몰용 배송 추적 연동 서비스',
      customer: '자사몰을 운영하는 중소 쇼핑몰',
      customerAlt: '택배 기사',
      customerCorrected: '월 주문 1천 건 이상 쇼핑몰',
      user: '쇼핑몰 CS 담당자',
      usageFrequency: '매일',
      payer: '쇼핑몰 대표',
      problem: '배송 문의 응대에 CS 시간이 너무 많이 드는 문제',
      problemAlt: '상품 사진 촬영 비용이 비싼 문제',
      alternative: '택배사 사이트 수동 조회',
      channel: '쇼핑몰 솔루션 앱마켓',
      differentiation: '여러 택배사를 한 번에 연동해 고객에게 자동 알림을 보내는 점',
      validation: '쇼핑몰 5곳의 배송 문의 건수 감소',
      revenue: '주문 건당 과금',
      teamSize: 5,
      city: '서울',
    },
    {
      archetype: 'Platform/API',
      oneLiner: '병원 예약 연동 위젯',
      customer: '동네 의원과 치과',
      customerAlt: '대학병원',
      customerCorrected: '피부과 의원',
      user: '병원 접수 직원',
      usageFrequency: '매일',
      payer: '병원 원장',
      problem: '전화 예약이 몰려 접수 직원이 다른 일을 못 하는 문제',
      problemAlt: '의료 장비가 비싼 문제',
      alternative: '전화 예약과 네이버 예약',
      channel: '의료 장비 대리점 제휴',
      differentiation: '기존 차트 프로그램과 바로 연동되는 점',
      validation: '의원 3곳의 전화 예약 비율 변화',
      revenue: '병원당 월 사용료',
      teamSize: 6,
      city: '광주',
    },
  ],
  [
    'hardware',
    {
      archetype: 'Hardware+SaaS',
      oneLiner: '공장 설비 진동 모니터링 센서',
      customer: '중소 제조 공장',
      customerAlt: '가정집',
      customerCorrected: '자동차 부품 2차 협력사',
      user: '설비 관리 담당자',
      usageFrequency: '매일',
      payer: '공장장',
      problem: '설비 고장을 미리 알지 못해 생산이 멈추는 문제',
      problemAlt: '공장 부지가 부족한 문제',
      alternative: '정기 점검과 작업자 감각',
      channel: '산업 전시회와 협력사 소개',
      differentiation: '설치 30분 만에 고장 징후를 알려주는 점',
      validation: '공장 2곳에서 3개월간 고장 예측 정확도',
      revenue: '센서 판매와 월 모니터링료',
      teamSize: 8,
      city: '창원',
    },
    {
      archetype: 'Hardware+SaaS',
      oneLiner: '스마트 화분 관리 기기',
      customer: '식물을 처음 키우는 1인 가구',
      customerAlt: '대형 농장',
      customerCorrected: '사무실 조경 담당자',
      user: '식물을 키우는 사람',
      usageFrequency: '매일',
      payer: '사용자 본인',
      problem: '물 주는 시기를 몰라 식물이 자꾸 죽는 문제',
      problemAlt: '화분이 무거운 문제',
      alternative: '알람 앱',
      channel: '온라인 식물 커뮤니티',
      differentiation: '흙 상태를 측정해 물 줄 때를 알려주는 점',
      validation: '체험단 30명의 식물 생존율',
      revenue: '기기 판매',
      teamSize: 4,
      city: '대전',
    },
  ],
  [
    'professional',
    {
      archetype: 'Professional Service',
      oneLiner: '초기 스타트업 GTM 실행 대행',
      customer: '시드 투자를 받은 초기 스타트업',
      customerAlt: '상장 기업',
      customerCorrected: '첫 제품을 막 출시한 스타트업',
      user: '스타트업 대표',
      usageFrequency: '프로젝트 기간 동안 매주',
      payer: '스타트업 대표',
      problem: '마케팅 인력 없이 첫 고객 확보 실행이 막히는 문제',
      problemAlt: '사무실 이전 문제',
      alternative: '프리랜서 마케터 단기 고용',
      channel: '액셀러레이터 데모데이',
      differentiation: '실행 결과에 연동된 성과 보수 구조',
      validation: '고객사 5곳의 첫 유료 고객 확보 기간',
      revenue: '월 리테이너와 성과 보수',
      teamSize: 5,
      city: '서울',
    },
    {
      archetype: 'Professional Service',
      oneLiner: '소상공인 노무 상담 서비스',
      customer: '직원 5명 미만 소상공인',
      customerAlt: '노무사',
      customerCorrected: '아르바이트생을 쓰는 카페 사장님',
      user: '사장님',
      usageFrequency: '문제가 생길 때마다',
      payer: '사장님',
      problem: '근로계약과 주휴수당 규정을 몰라 분쟁이 생기는 문제',
      problemAlt: '임대료 인상 문제',
      alternative: '인터넷 검색과 지인 상담',
      channel: '소상공인 지원센터 교육',
      differentiation: '카카오톡으로 바로 노무사 답변을 받는 점',
      validation: '시범 상담 100건의 재상담률',
      revenue: '월 구독 상담료',
      teamSize: 3,
      city: '인천',
    },
  ],
  [
    'ai-service',
    {
      archetype: 'AI Service',
      oneLiner: 'PM용 AI 문서 분석 도구',
      customer: 'IT 기업의 PM과 기획자',
      customerAlt: '고등학교 교사',
      customerCorrected: '에이전시 프로젝트 매니저',
      user: 'PM 본인',
      usageFrequency: '매일',
      payer: '팀 리더',
      problem: '회의록과 요구사항 문서를 정리하는 데 시간이 너무 많이 드는 문제',
      problemAlt: '채용이 어려운 문제',
      alternative: '노션과 수작업 정리',
      channel: 'PM 커뮤니티와 링크드인',
      differentiation: '요구사항 변경 이력을 자동으로 추적하는 점',
      validation: 'PM 20명의 문서 정리 시간 측정',
      revenue: '좌석당 월 구독',
      teamSize: 4,
      city: '판교',
    },
    {
      archetype: 'AI Service',
      oneLiner: '쇼핑몰 상세페이지 AI 카피 생성',
      customer: '1인 온라인 셀러',
      customerAlt: '광고 대행사',
      customerCorrected: '스마트스토어 초보 셀러',
      user: '셀러 본인',
      usageFrequency: '신상품 올릴 때마다',
      payer: '셀러 본인',
      problem: '상세페이지 문구를 쓰는 데 하루가 걸리는 문제',
      problemAlt: '재고 관리가 어려운 문제',
      alternative: '외주 카피라이터',
      channel: '셀러 교육 유튜브',
      differentiation: '판매 데이터를 보고 잘 팔리는 문구로 고쳐주는 점',
      validation: '셀러 30명의 전환율 비교',
      revenue: '생성 건수 과금',
      teamSize: 2,
      city: '서울',
    },
  ],
];

export const STRESS_BUSINESS_UNIVERSE: StressBusinessTruth[] = SEEDS.flatMap(([key, a, b]) => [
  { ...a, id: `st-${key}-1`, docStyle: 'structured' as const, documentText: structuredDoc(a) },
  { ...b, id: `st-${key}-2`, docStyle: 'prose' as const, documentText: proseDoc(b) },
]);
