'use client';

import { useTranslations } from 'next-intl';
import { Sparkles } from 'lucide-react';

import { cn } from '@repo/ui/lib/utils';

type WorkflowStackBadgesProps = {
  className?: string;
};

const STACK_KEYS = ['startup', 'pm', 'investment'] as const;

export function WorkflowStackBadges({ className }: WorkflowStackBadgesProps) {
  const t = useTranslations('workflow.confirmation.stack');

  return (
    <div className={cn('rounded-xl border border-primary/20 bg-primary/[0.04] p-4', className)}>
      <p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">
        <Sparkles className="size-3.5" aria-hidden />
        {t('label')}
      </p>
      <p className="mt-1 text-sm text-muted-foreground">{t('desc')}</p>
      <div className="mt-3 flex flex-wrap items-center gap-2">
        {STACK_KEYS.map((key, index) => (
          <span key={key} className="inline-flex items-center gap-1.5">
            <span className="rounded-full bg-background px-3 py-1.5 text-sm font-medium text-foreground shadow-sm ring-1 ring-border/60">
              {t(key)}
            </span>
            {index < STACK_KEYS.length - 1 ? (
              <span className="text-muted-foreground" aria-hidden>
                ×
              </span>
            ) : null}
          </span>
        ))}
      </div>
      <p className="mt-2 text-xs text-muted-foreground">{t('autoGenerated')}</p>
    </div>
  );
}
