import type { AuthRole } from '../domain/role';
import type { Permission } from '../domain/permission';
import { ALL_PERMISSIONS, PERMISSIONS } from '../domain/permission';

/** RBAC: Role → Permission mapping. Customize per tenant without code changes. */
export const ROLE_PERMISSION_MAP: Record<AuthRole, Permission[]> = {
  super_admin: [...ALL_PERMISSIONS],
  admin: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.ORGANIZATIONS_READ,
    PERMISSIONS.ORGANIZATIONS_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
  ],
  manager: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.ORGANIZATIONS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],
  editor: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.ORGANIZATIONS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  member: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.ORGANIZATIONS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  guest: [PERMISSIONS.PROJECTS_READ, PERMISSIONS.ORGANIZATIONS_READ],
};
